[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "persian-number-to-word"      # اسم پکیج در PyPI
version = "1.1.0"                     # شماره نسخه
description = "تبدیل اعداد به حروف فارسی بدون محدودیت"
readme = "README.md"
authors = [{ name = "Poriya", email = "poria.dell7@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://github.com/p7deli/persian-number-to-word"

[tool.setuptools.packages.find]
where = ["src"]